version: "3"
services:
  sp:
    platform: linux/amd64
    build:
      context: ./sp
      dockerfile: Dockerfile
    working_dir: /usr/src/sp/
    volumes:
      - ./sp:/usr/src/sp
    ports:
      - 80:80
      - 443:443
    networks:
      - front
  
  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    working_dir: /usr/src/app/
    volumes:
      - ./app:/usr/src/app
    ports:
      - 18080:8080
    # expose:
    #   - 8080
    networks:
      - front

networks:
  front:
    external: false
